services:
  api:
    image: r0maf/api-course
    depends_on:
      - postgres
    ports:
      - 80:8000
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 && alembic upgrade head

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: